declare module 'bundle-text:*' {
  const value: string;
  export default value;
}

/**
 * We use the magic "locales" scheme to import files that are generated by
 * lit-localize. Running lit-localize and resolving these magic specifiers
 * happen in scripts/parcel-resolver-locale.mjs.
 */
declare module 'locales:config' {
  export const sourceLocale: string;
  export const targetLocales: string[];
  export const allLocales: string[];
}
declare module 'locales:*' {
  import { TemplateMap } from '@lit/localize';
  export const templates: TemplateMap;
}
