import { MsgFn } from './i18n/msg';

export type StateInfo = {
  name: (msg: MsgFn) => string;
};

/**
 * States that are supported for customization.
 */
export const STATES: Record<string, StateInfo> = {
  AK: { name: msg => msg('Alaska') },
  AL: { name: msg => msg('Alabama') },
  AR: { name: msg => msg('Arkansas') },
  AZ: { name: msg => msg('Arizona') },
  CA: { name: msg => msg('California') },
  CO: { name: msg => msg('Colorado') },
  CT: { name: msg => msg('Connecticut') },
  DC: { name: msg => msg('Washington, DC') },
  DE: { name: msg => msg('Delaware') },
  FL: { name: msg => msg('Florida') },
  GA: { name: msg => msg('Georgia') },
  HI: { name: msg => msg('Hawaii') },
  IA: { name: msg => msg('Iowa') },
  ID: { name: msg => msg('Idaho') },
  IL: { name: msg => msg('Illinois') },
  IN: { name: msg => msg('Indiana') },
  KS: { name: msg => msg('Kansas') },
  KY: { name: msg => msg('Kentucky') },
  LA: { name: msg => msg('Louisiana') },
  MA: { name: msg => msg('Massachusetts') },
  MD: { name: msg => msg('Maryland') },
  ME: { name: msg => msg('Maine') },
  MI: { name: msg => msg('Michigan') },
  MN: { name: msg => msg('Minnesota') },
  MO: { name: msg => msg('Missouri') },
  MS: { name: msg => msg('Mississippi') },
  MT: { name: msg => msg('Montana') },
  NC: { name: msg => msg('North Carolina') },
  ND: { name: msg => msg('North Dakota') },
  NE: { name: msg => msg('Nebraska') },
  NH: { name: msg => msg('New Hampshire') },
  NJ: { name: msg => msg('New Jersey') },
  NM: { name: msg => msg('New Mexico') },
  NV: { name: msg => msg('Nevada') },
  NY: { name: msg => msg('New York') },
  OH: { name: msg => msg('Ohio') },
  OK: { name: msg => msg('Oklahoma') },
  OR: { name: msg => msg('Oregon') },
  PA: { name: msg => msg('Pennsylvania') },
  RI: { name: msg => msg('Rhode Island') },
  SC: { name: msg => msg('South Carolina') },
  SD: { name: msg => msg('South Dakota') },
  TN: { name: msg => msg('Tennessee') },
  TX: { name: msg => msg('Texas') },
  UT: { name: msg => msg('Utah') },
  VA: { name: msg => msg('Virginia') },
  VT: { name: msg => msg('Vermont') },
  WA: { name: msg => msg('Washington') },
  WI: { name: msg => msg('Wisconsin') },
  WV: { name: msg => msg('West Virginia') },
  WY: { name: msg => msg('Wyoming') },
};
